---
title: "World Population"
output: html_document
date: "Last Update: `r format(Sys.Date(), '%B %d %Y')`"
---

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(forecast)
library(DT)
library(rvest)
knitr::opts_chunk$set(fig.width = unit(20, "cm"), fig.height = unit(10, "cm"))
# 1_IMPORT ---------------------------------------------------------------------

content <- rvest::read_html("https://www.worldometers.info/world-population/population-by-country/")
df <- rvest::html_table(content) %>% pluck(1)

df %>% 
  clean_names() %>%
  select(2:ncol(.)) %>% 
  rename(country = 1,
         pop_2020 = 2,
         yearly_change_per = 3,
         density_km2 = 5,
         area_km2 = 6,
         urban_pop_per = 10) %>% 
  mutate_all(parse_guess) %>% 
  mutate_all(.tbl = ., ~str_replace_all(.,pattern = "N.A.", replacement = "0")) %>% 
  mutate_all(~str_remove_all(., pattern = " %")) %>% 
  mutate_all(~str_replace_na(.,replacement = "0")) %>% 
  mutate_all(parse_guess) -> df

```
#### This data was taken from [Worldometers](<https://www.worldometers.info/world-population/population-by-country/>).

# Top 20 Countries


```{r cars, echo=FALSE}
df %>% 
  arrange(desc(pop_2020)) %>% 
  select(1,2,9,11) %>% 
  mutate(country = str_replace(country, pattern = "United States", replacement = "USA")) %>% 
  mutate(country = str_replace(country, pattern = "United Kingdom", replacement = "UK")) %>%
  mutate(country = as_factor(country),
         country = fct_inorder(country)) %>%
  head(20) -> df_20

df_20 %>% 
  mutate(world_share = world_share/100) -> df_20

datatable(df_20, 
          extensions = c('Responsive','Buttons'), options = list(
            pageLength = 20)) %>% 
  DT::formatPercentage("world_share",2)
```

## Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}

df_20 %>% 
ggplot(aes(x = country,
             y = pop_2020,
             fill = country)) +
  
  geom_bar(stat = "identity", color = "black", show.legend = F) +
  geom_text(aes(label = scales::number(x = pop_2020, scale = .000000001, accuracy = .01),
                y = pop_2020 + 30000000),
            size = 6) +
  
  scale_y_continuous(labels = scales::number_format(scale = .000000001, suffix = " B", accuracy = .1)) +
  scale_fill_viridis_d(option = "turbo") +
  labs(title = "", subtitle = "",x = "", y = "") +
  theme_classic() +
  theme(axis.text = element_text(size = 14)) -> p1

p1

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
